### ISSUE TITLE
Applying E2E Model on New Data

### ISSUE THREAD

**Issue by JosephGatto** [ej0cl6/TextEE#1]
Hi, 

Can you provide any information/demo code on how to transform an unlabeled string into a silver-labeled event record with an E2E model? 

Thanks!

**Comment by ej0cl6** [comment]
We will release the sample code for applying trained models to new data soon. Please stay tuned!

**Comment by ej0cl6** [comment]
We have updated the scripts. You can use the following command to apply an existing E2E model for new texts.

```
python TextEE/predict_end2end.py --input_file demo_input.txt --model [saved_model_folder] --output_file demo_output.json
```

Please see https://github.com/ej0cl6/TextEE/tree/main?tab=readme-ov-file#making-predictions-for-new-texts-with-end-to-end-model for more details. Thanks!
