### ISSUE TITLE
Can not run prediction for new datasets

### ISSUE THREAD

**Issue by hoangthuytruc** [ej0cl6/TextEE#4]
Hello,

I'am trying to run this repo for evaluating it on my datasets. Could you tell me where to get [saved_models_folder] in two prediction commands at the section "Making Predictions for New Texts". Is it the "TextEE/models" folder? Or somewhere else? 

Thanks.

**Comment by hoangthuytruc** [comment]
Btw, I am working in the Kaggle notebook. The command I use the prediction command as below. 

```
!/opt/conda/envs/textee/bin/python3.8 TextEE/predict_pipeline.py --input_file demo_input.txt --ed_model TextEE/models --eae_model TextEE/models --output_file demo_output.json
```
And I get this error:

<img width="801" alt="Screenshot 2024-07-02 at 16 07 30" src="https://github.com/ej0cl6/TextEE/assets/25169385/2cc2d6f8-aeb7-4eaf-8e68-5580e762b2c6">

Could you show me where it not working?

**Comment by ej0cl6** [comment]
> Hello,
> 
> I'am trying to run this repo for evaluating it on my datasets. Could you tell me where to get [saved_models_folder] in two prediction commands at the section "Making Predictions for New Texts". Is it the "TextEE/models" folder? Or somewhere else?
> 
> Thanks.

`[saved_model_folder]` is the saved checkpoint during training. Currently, we do not release any pre-trained models. Therefore, you may choose to train your own model with the command [here](https://github.com/ej0cl6/TextEE?tab=readme-ov-file#training). After training, `[saved_model_folder]` should be set as the folder under the `output_dir` in the config file. An example is [here](https://github.com/ej0cl6/TextEE/blob/main/config/ace05-en/DyGIEpp_E2E_ace05-en_roberta-large.jsonnet#L18).

**Comment by ej0cl6** [comment]
> Btw, I am working in the Kaggle notebook. The command I use the prediction command as below.
> 
> ```
> !/opt/conda/envs/textee/bin/python3.8 TextEE/predict_pipeline.py --input_file demo_input.txt --ed_model TextEE/models --eae_model TextEE/models --output_file demo_output.json
> ```
> 
> And I get this error:
> 
> <img alt="Screenshot 2024-07-02 at 16 07 30" width="801" src="https://private-user-images.githubusercontent.com/25169385/344956961-2cc2d6f8-aeb7-4eaf-8e68-5580e762b2c6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5NjI4ODQsIm5iZiI6MTcxOTk2MjU4NCwicGF0aCI6Ii8yNTE2OTM4NS8zNDQ5NTY5NjEtMmNjMmQ2ZjgtYWViNy00ZWFmLThlNjgtNTU4MGU3NjJiMmM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAyVDIzMjMwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxYTQ3OWUzY2I1NWUwZmFiOGJlMjNmOWE4Nzk3MTk4MzExNjhlOTg1YTRjY2UyNTc5ZjgxYTFkY2Y1ZDgzYTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.k76n4htZTOn20hhJ5usiQi74cuMsHs6sPdkSD8nxIJc">
> Could you show me where it not working?

Thanks for pointing out. We forgot to remove it in our internal test for LLMs. We've fixed it now.

**Comment by hoangthuytruc** [comment]
> > Hello,
> > I'am trying to run this repo for evaluating it on my datasets. Could you tell me where to get [saved_models_folder] in two prediction commands at the section "Making Predictions for New Texts". Is it the "TextEE/models" folder? Or somewhere else?
> > Thanks.
> 
> `[saved_model_folder]` is the saved checkpoint during training. Currently, we do not release any pre-trained models. Therefore, you may choose to train your own model with the command [here](https://github.com/ej0cl6/TextEE?tab=readme-ov-file#training). After training, `[saved_model_folder]` should be set as the folder under the `output_dir` in the config file. An example is [here](https://github.com/ej0cl6/TextEE/blob/main/config/ace05-en/DyGIEpp_E2E_ace05-en_roberta-large.jsonnet#L18).

I got it. Thank you for your reply.
